#!/usr/bin/perl

##--[  Script config  ]--------------------------------------------------------

my $quiet  = 1;
my $args   = "";

##--[  Run  ]------------------------------------------------------------------

# Compile source if there is no "./target" directory
system("mvn compile") unless (-d "./target/");

my $q       = $quiet ? "--quiet -e" : "";
my $xargs   = $args . " " . join(" ", @ARGV);

system("mvn $q exec:java -Dexec.args=\"$xargs\"");

