#!/usr/bin/perl

##--[  Script config  ]--------------------------------------------------------

my $quiet  = 1;
my $args   = "";
my $class  = "cz.muni.pa165.surrealtravel.Program";

##--[  Run  ]------------------------------------------------------------------

# Compile source if there is no "./target" directory
system("mvn compile") unless (-d "./target/");

my $command = "mvn";
my $q       = $quiet ? "--quiet" : "";
my $xargs   = $args . " " . join(" ", @ARGV);

system("mvn $q exec:java -Dexec.mainClass=\"$class\" -Dexec.args=\"$xargs\"");

